#
# UDP Protocol LIB makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile
ROOT_PATH=../../../..

include $(ROOT_PATH)/Makefile.defs
NAME=udp.so
LIBS=

include $(ROOT_PATH)/Makefile.libs
