# $Id: Makefile 5901 2009-07-21 07:45:05Z bogdan_iancu $
#
# MI_FIFO module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile
ROOT_PATH=../../../..

include $(ROOT_PATH)/Makefile.defs
NAME=mi_stream.so
LIBS=

include $(ROOT_PATH)/Makefile.libs
